"""Three-dimensional SirenFNO for channels-first lightcone cubes."""

from __future__ import annotations

import math
from pathlib import Path
from typing import Sequence

import torch
import torch.nn as nn
import torch.nn.functional as F

from util.spatial import pad_lightcone_spatial


class FourierFeatureMapping(nn.Module):
    """Encode signed Fourier-mode coordinates with random Fourier features."""

    def __init__(
        self,
        input_dim: int = 3,
        feature_dim: int = 16,
        sigma: float = 128.0,
        learnable: bool = True,
    ):
        super().__init__()
        if feature_dim <= 0 or feature_dim % 2:
            raise ValueError("feature_dim must be a positive even integer")
        self.input_dim = int(input_dim)
        self.feature_dim = int(feature_dim)
        projection = torch.randn(self.input_dim, self.feature_dim // 2) * float(sigma)
        self.projection = nn.Parameter(projection, requires_grad=bool(learnable))

    def forward(self, coordinates: torch.Tensor) -> torch.Tensor:
        if coordinates.shape[-1] != self.input_dim:
            raise ValueError(
                f"Expected coordinate dimension {self.input_dim}, "
                f"got {coordinates.shape[-1]}"
            )
        phase = torch.matmul(coordinates, self.projection) * math.pi
        return torch.cat((torch.cos(phase), torch.sin(phase)), dim=-1)


class SineLayer(nn.Module):
    """Bias-free SIREN layer with a learnable per-feature frequency scale."""

    def __init__(self, in_features: int, out_features: int, omega: float):
        super().__init__()
        self.linear = nn.Linear(in_features, out_features, bias=False)
        self.omega = nn.Parameter(torch.full((out_features,), float(omega)))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return torch.sin(self.linear(x) * self.omega)


class SirenWeightNetwork(nn.Module):
    """Map signed 3-D mode coordinates to dense channel-mixing weights."""

    def __init__(
        self,
        out_dim: int,
        hidden_dim: int = 64,
        omega: float = 30.0,
        n_hidden: int = 1,
        feature_dim: int = 16,
        ff_sigma: float = 128.0,
        learnable_ff: bool = True,
    ):
        super().__init__()
        if n_hidden < 1:
            raise ValueError("n_hidden must be at least 1")
        self.mapping = FourierFeatureMapping(
            input_dim=3,
            feature_dim=feature_dim,
            sigma=ff_sigma,
            learnable=learnable_ff,
        )
        self.first = SineLayer(feature_dim, hidden_dim, omega)
        self.hidden = nn.ModuleList(
            SineLayer(hidden_dim, hidden_dim, omega)
            for _ in range(n_hidden - 1)
        )
        self.last = nn.Linear(hidden_dim, out_dim, bias=False)
        self._initialize(feature_dim=feature_dim, hidden_dim=hidden_dim, omega=omega)

    def _initialize(self, feature_dim: int, hidden_dim: int, omega: float) -> None:
        with torch.no_grad():
            self.first.linear.weight.uniform_(-1.0 / feature_dim, 1.0 / feature_dim)
            bound = math.sqrt(6.0 / hidden_dim) / float(omega)
            for layer in self.hidden:
                layer.linear.weight.uniform_(-bound, bound)
            self.last.weight.uniform_(-bound, bound)

    def forward(self, coordinates: torch.Tensor) -> torch.Tensor:
        x = self.first(self.mapping(coordinates))
        for layer in self.hidden:
            x = layer(x)
        return self.last(x)


class SpectralConv3dSiren(nn.Module):
    """Truncated 3-D Fourier convolution whose weights are generated by SIRENs.

    ``rfftn`` stores positive and negative frequencies on X/Y, while only the
    non-negative half-spectrum is stored on Z. Accordingly, this layer fills
    four signed X/Y quadrants and one non-negative Z range.
    """

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        n_modes: Sequence[int],
        hidden_dim: int = 64,
        omega: float = 30.0,
        n_hidden: int = 1,
        feature_dim: int = 16,
        ff_sigma: float = 128.0,
        learnable_ff: bool = True,
        dropout: float = 0.0,
    ):
        super().__init__()
        if len(n_modes) != 3:
            raise ValueError("n_modes must contain exactly three values")
        if any(int(mode) <= 0 for mode in n_modes):
            raise ValueError("all retained mode counts must be positive")
        self.in_channels = int(in_channels)
        self.out_channels = int(out_channels)
        self.n_modes = tuple(int(mode) for mode in n_modes)
        self.dropout = float(dropout)
        weight_dim = self.in_channels * self.out_channels
        self.real_weight = SirenWeightNetwork(
            weight_dim, hidden_dim, omega, n_hidden,
            feature_dim, ff_sigma, learnable_ff,
        )
        self.imag_weight = SirenWeightNetwork(
            weight_dim, hidden_dim, omega, n_hidden,
            feature_dim, ff_sigma, learnable_ff,
        )
        self.bias = nn.Parameter(torch.zeros(self.out_channels, 1, 1, 1))

    @staticmethod
    def _contract(x: torch.Tensor, weight: torch.Tensor) -> torch.Tensor:
        return torch.einsum("bixyz,ioxyz->boxyz", x, weight)

    def _validate_modes(self, spatial_shape: Sequence[int]) -> None:
        nx, ny, nz = (int(size) for size in spatial_shape)
        mx, my, mz = self.n_modes
        limits = (nx // 2, ny // 2, nz // 2 + 1)
        if mx > limits[0] or my > limits[1] or mz > limits[2]:
            raise ValueError(
                f"n_modes={self.n_modes} exceeds FFT limits {limits} "
                f"for spatial shape {(nx, ny, nz)}"
            )

    def _quadrant_coordinates(
        self,
        spatial_shape: Sequence[int],
        *,
        device: torch.device,
        dtype: torch.dtype,
    ) -> list[torch.Tensor]:
        mx, my, mz = self.n_modes
        # Normalize by the retained band rather than the input resolution.
        # The same learned spectral function is therefore evaluated at the
        # same coordinates when the physical grid resolution changes.
        scale_x = max(1, mx)
        scale_y = max(1, my)
        scale_z = max(1, mz - 1)
        positive_x = torch.arange(mx, device=device, dtype=dtype) / scale_x
        negative_x = torch.arange(-mx, 0, device=device, dtype=dtype) / scale_x
        positive_y = torch.arange(my, device=device, dtype=dtype) / scale_y
        negative_y = torch.arange(-my, 0, device=device, dtype=dtype) / scale_y
        positive_z = torch.arange(mz, device=device, dtype=dtype) / scale_z

        def grid(kx: torch.Tensor, ky: torch.Tensor) -> torch.Tensor:
            values = torch.meshgrid(kx, ky, positive_z, indexing="ij")
            return torch.stack(values, dim=-1)

        return [
            grid(positive_x, positive_y),
            grid(negative_x, positive_y),
            grid(positive_x, negative_y),
            grid(negative_x, negative_y),
        ]

    def _make_weight(self, coordinates: torch.Tensor) -> torch.Tensor:
        mx, my, mz = self.n_modes
        real = self.real_weight(coordinates)
        imag = self.imag_weight(coordinates)
        shape = (mx, my, mz, self.in_channels, self.out_channels)
        real = real.reshape(shape).permute(3, 4, 0, 1, 2).contiguous()
        imag = imag.reshape(shape).permute(3, 4, 0, 1, 2).contiguous()
        return torch.complex(real, imag)

    def spectral_weight_tensors(
        self,
        spatial_shape: Sequence[int] | None = None,
    ) -> list[torch.Tensor]:
        """Materialize the four retained weight blocks for diagnostics."""
        if spatial_shape is None:
            mx, my, mz = self.n_modes
            spatial_shape = (2 * mx, 2 * my, max(2, 2 * (mz - 1)))
        self._validate_modes(spatial_shape)
        parameter = next(self.parameters())
        coordinates = self._quadrant_coordinates(
            spatial_shape,
            device=parameter.device,
            dtype=parameter.dtype,
        )
        return [self._make_weight(grid) for grid in coordinates]

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if x.ndim != 5:
            raise ValueError(f"Expected input shape (B,C,X,Y,Z), got {tuple(x.shape)}")
        if x.shape[1] != self.in_channels:
            raise ValueError(
                f"Expected {self.in_channels} input channels, got {x.shape[1]}"
            )
        spatial_shape = tuple(int(size) for size in x.shape[-3:])
        self._validate_modes(spatial_shape)
        mx, my, mz = self.n_modes
        x_ft = torch.fft.rfftn(x, dim=(-3, -2, -1))
        out_ft = torch.zeros(
            x.shape[0],
            self.out_channels,
            spatial_shape[0],
            spatial_shape[1],
            spatial_shape[2] // 2 + 1,
            dtype=x_ft.dtype,
            device=x.device,
        )
        coordinates = self._quadrant_coordinates(
            spatial_shape,
            device=x.device,
            dtype=x.dtype,
        )
        blocks = (
            (slice(0, mx), slice(0, my)),
            (slice(-mx, None), slice(0, my)),
            (slice(0, mx), slice(-my, None)),
            (slice(-mx, None), slice(-my, None)),
        )
        for coordinate_grid, (x_slice, y_slice) in zip(
            coordinates, blocks, strict=True
        ):
            weight = self._make_weight(coordinate_grid).to(dtype=x_ft.dtype)
            out_ft[:, :, x_slice, y_slice, :mz] = self._contract(
                x_ft[:, :, x_slice, y_slice, :mz],
                weight,
            )
        out = torch.fft.irfftn(
            out_ft,
            s=spatial_shape,
            dim=(-3, -2, -1),
        )
        if self.dropout and self.training:
            out = F.dropout(out, p=self.dropout)
        return out + self.bias


class PointwiseMLP3d(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        hidden_channels: int,
        dropout: float = 0.0,
    ):
        super().__init__()
        self.first = nn.Conv3d(in_channels, hidden_channels, kernel_size=1)
        self.last = nn.Conv3d(hidden_channels, out_channels, kernel_size=1)
        self.dropout = float(dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = F.gelu(self.first(x))
        if self.dropout and self.training:
            x = F.dropout(x, p=self.dropout)
        return self.last(x)


class SirenFNO3d(nn.Module):
    """Residual 3-D FNO with SIREN-generated truncated spectral weights."""

    def __init__(
        self,
        n_modes: Sequence[int],
        hidden_channels: int,
        in_channels: int,
        out_channels: int = 1,
        n_layers: int = 4,
        padding: Sequence[int] = (0, 0, 8),
        add_grid: bool = True,
        siren_hidden_dim: int = 64,
        siren_omega: float = 30.0,
        siren_n_hidden: int = 1,
        siren_feature_dim: int = 16,
        siren_ff_sigma: float = 128.0,
        siren_learnable_ff: bool = True,
        mlp_dropout: float = 0.0,
    ):
        super().__init__()
        if len(padding) != 3 or any(int(value) < 0 for value in padding):
            raise ValueError(
                "padding must contain three non-negative values "
                "(pad_x, pad_y, pad_z)"
            )
        if n_layers <= 0:
            raise ValueError("n_layers must be positive")
        self.n_modes = tuple(int(value) for value in n_modes)
        self.hidden_channels = int(hidden_channels)
        self.in_channels = int(in_channels)
        self.out_channels = int(out_channels)
        self.n_layers = int(n_layers)
        self.padding = tuple(int(value) for value in padding)
        self.add_grid = bool(add_grid)

        lift_channels = self.in_channels + (3 if self.add_grid else 0)
        self.lifting = nn.Conv3d(lift_channels, self.hidden_channels, kernel_size=1)
        self.spectral_layers = nn.ModuleList(
            SpectralConv3dSiren(
                self.hidden_channels,
                self.hidden_channels,
                self.n_modes,
                hidden_dim=siren_hidden_dim,
                omega=siren_omega,
                n_hidden=siren_n_hidden,
                feature_dim=siren_feature_dim,
                ff_sigma=siren_ff_sigma,
                learnable_ff=siren_learnable_ff,
                dropout=mlp_dropout,
            )
            for _ in range(self.n_layers)
        )
        self.channel_mlps = nn.ModuleList(
            PointwiseMLP3d(
                self.hidden_channels,
                self.hidden_channels,
                4 * self.hidden_channels,
                dropout=mlp_dropout,
            )
            for _ in range(self.n_layers)
        )
        self.projection = PointwiseMLP3d(
            self.hidden_channels,
            self.out_channels,
            4 * self.hidden_channels,
        )

    @staticmethod
    def _make_grid(
        batch: int,
        nx: int,
        ny: int,
        nz: int,
        *,
        device: torch.device,
        dtype: torch.dtype,
    ) -> torch.Tensor:
        axes = [
            torch.linspace(0.0, 1.0, size, device=device, dtype=dtype)
            for size in (nx, ny, nz)
        ]
        grid = torch.stack(torch.meshgrid(*axes, indexing="ij"), dim=0)
        return grid.unsqueeze(0).expand(batch, -1, -1, -1, -1)

    def forward(self, x: torch.Tensor | None = None, **kwargs) -> torch.Tensor:
        if x is None:
            x = kwargs.get("x")
        if x is None:
            raise TypeError("SirenFNO3d.forward expected argument 'x'")
        if x.ndim != 5:
            raise ValueError(f"Expected input shape (B,C,X,Y,Z), got {tuple(x.shape)}")
        batch, channels, nx, ny, nz = x.shape
        if self.add_grid:
            if channels == self.in_channels:
                x = torch.cat(
                    (
                        x,
                        self._make_grid(
                            batch, nx, ny, nz, device=x.device, dtype=x.dtype
                        ),
                    ),
                    dim=1,
                )
            elif channels != self.in_channels + 3:
                raise ValueError(
                    f"Expected {self.in_channels} or {self.in_channels + 3} "
                    f"channels, got {channels}"
                )
        elif channels != self.in_channels:
            raise ValueError(
                f"Expected {self.in_channels} input channels, got {channels}"
            )

        x = self.lifting(x)
        pad_x, pad_y, pad_z = self.padding
        if any(self.padding):
            x = pad_lightcone_spatial(x, pad_x, pad_y, pad_z)

        for index, (spectral, channel_mlp) in enumerate(
            zip(self.spectral_layers, self.channel_mlps, strict=True)
        ):
            residual = channel_mlp(spectral(x))
            x = x + residual
            if index + 1 < self.n_layers:
                x = F.gelu(x)

        if any(self.padding):
            x = x[:, :, :nx, :ny, :nz]
        return self.projection(x)

    def save_checkpoint(self, save_folder, save_name: str) -> None:
        save_folder = Path(save_folder)
        save_folder.mkdir(parents=True, exist_ok=True)
        torch.save(
            self.state_dict(),
            (save_folder / f"{save_name}_state_dict.pt").as_posix(),
        )

    def load_checkpoint(self, save_folder, save_name: str, map_location=None) -> None:
        path = Path(save_folder) / f"{save_name}_state_dict.pt"
        self.load_state_dict(
            torch.load(path, map_location=map_location, weights_only=False)
        )
